// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0TzdYQWPLArN0u4Jsi9pscYP5WKAuVEc',
    appId: '1:556380855257:web:8c068989cae1adde22d7c8',
    messagingSenderId: '556380855257',
    projectId: 'facegate-3f84d',
    authDomain: 'facegate-3f84d.firebaseapp.com',
    storageBucket: 'facegate-3f84d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRaufz3bi68SyPCI_0ssbDt_GKNiiT1aQ',
    appId: '1:556380855257:android:d7c5d1e16aceca0122d7c8',
    messagingSenderId: '556380855257',
    projectId: 'facegate-3f84d',
    storageBucket: 'facegate-3f84d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3cVNZ2F4YQIvQRIgyAe4QCdUz013WIH8',
    appId: '1:556380855257:ios:bedac7b54110fff522d7c8',
    messagingSenderId: '556380855257',
    projectId: 'facegate-3f84d',
    storageBucket: 'facegate-3f84d.firebasestorage.app',
    iosBundleId: 'com.example.facegate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3cVNZ2F4YQIvQRIgyAe4QCdUz013WIH8',
    appId: '1:556380855257:ios:bedac7b54110fff522d7c8',
    messagingSenderId: '556380855257',
    projectId: 'facegate-3f84d',
    storageBucket: 'facegate-3f84d.firebasestorage.app',
    iosBundleId: 'com.example.facegate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0TzdYQWPLArN0u4Jsi9pscYP5WKAuVEc',
    appId: '1:556380855257:web:da6524cf6a3d659822d7c8',
    messagingSenderId: '556380855257',
    projectId: 'facegate-3f84d',
    authDomain: 'facegate-3f84d.firebaseapp.com',
    storageBucket: 'facegate-3f84d.firebasestorage.app',
  );

}